openapi: 3.0.0
info:
  title: 支付页信息
  version: '1.0'
  description: 获取支付页面信息
servers:
  - url: 'http://localhost:3000'
paths:
  /payment-info:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  commodity:
                    type: object
                  specification:
                    type: array
                    items: {}
      operationId: get-payment-info
      parameters:
        - schema:
            type: string
          in: query
          name: commodityId
          description: 商品ID
        - schema:
            type: string
          in: query
          name: specificationId
          description: 规格ID
        - schema:
            type: string
          in: query
          name: channelId
          description: 渠道ID
        - schema:
            type: string
          in: query
          name: invitationId
          description: 邀请码
        - schema:
            type: string
          in: query
          name: userId
          description: 用户ID
          required: true
        - schema:
            type: string
          in: query
          name: itemId
          description: 子产品ID(资讯ID)
        - schema:
            type: string
          in: query
          name: payMethod
          description: 支付方式
          required: true
      description: ''
    parameters:
      - schema:
          type: string
        name: commodityId
        in: query
        description: 商品Id
  /payment:
    post:
      summary: ''
      operationId: post-payment
      responses:
        '200':
          description: OK
      description: 支付下单
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commodityId:
                  type: string
                  description: 商品ID
                specificationId:
                  type: string
                  description: 规格ID
                channelId:
                  type: string
                  description: 渠道ID
                invitationId:
                  type: string
                  description: 邀请码
                userId:
                  type: string
                  description: 用户ID
                itemId:
                  type: string
                  description: 子产品ID（资讯ID）
                payMethod:
                  type: string
                  description: 支付方式
              required:
                - payMethod
        description: ''
components:
  schemas: {}
